backend/config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:create, :destroy, :index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:create]
  resources :sessions, only: [:create, :index]

  delete 'logout' => 'sessions#destroy', as: :log_out
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

backend/app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: {minimum: 8}
  validates :password, confirmation: true
  validates :email, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}

  has_many :messages
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  skip_before_action :verify_authenticity_token

  def not_authenticated
    render json: {error: 'You must be logged in to do this action.'}, status: 403
  end
end

backend/app/controllers/messages_controller.rb
require 'twilio-ruby'

class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show update destroy ]

  def initialize
    @twilio_client = Twilio::REST::Client.new(ENV['TWILIO_SID'], ENV['TWILIO_SECRET'], ENV['TWILIO_USER_SID'])
  end

  # GET /messages or /messages.json
  def index
    @messages = Message.where(user: current_user).all

    render json: { messages: @messages }
  end

  # GET /messages/1 or /messages/1.json
  def show
    render json: { message: @message }
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new({**message_params, user: current_user})

    if @message.save && send_sms
      render json: { status: :created, location: @message }
    else
      @message.destroy! if @message.save
      render json: { error: @message.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    if @message.update(message_params)
      render json: { status: :ok, message: @message }
    else
      render json: { error: @message.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy!

    render json: { notice: "Message was successfully destroyed." }
  end

  private

  def send_sms
    return nil unless @twilio_client

    begin
      message = @twilio_client.messages.create(
        body: @message.text,
        to: @message.phone_number,
        from: ENV['TWILIO_PHONE_NUMBER'],
      )

      return message
    rescue Twilio::REST::RestError => e
      puts e.message
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.permit(:phone_number, :text)
  end
end

backend/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create]

  def index
    puts 'current user:', current_user
    if logged_in?
      render json: {success: 'session exists'}
    else
      render json: {error: 'session not found'}, status: 400
    end
  end
  
  def create
    @user = login(sessions_params[:email], sessions_params[:password])
    puts 'user:', @user
    if @user
      session[:user_id] = @user.id
      render json: {success: 'login successful'}
    else
      render json: {error: 'Could not login'}, status: 400
    end
  end
  
  def destroy
    if logout
      render json: {success: 'logged out'}
    else
      render json: {error: 'Could not log out'}, status: 400
    end
  end

  private

  def sessions_params
    params.require(:session).permit(:email, :password)
  end
end

backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:create]

  def create
    @user = User.new(user_params)
    if @user.save
      render json: {success: "User created!"}
    else
      render json: {**@user.errors}, status: 400
    end
  end

  private

  def user_params
    params.permit(:email, :password, :password_confirmation)
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/messages_helper.rb
module MessagesHelper
end

backend/app/helpers/session_helper.rb
module SessionHelper
end

backend/app/helpers/users_helper.rb
module UsersHelper
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :delivered %>
    <%= form.datetime_select :delivered %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

backend/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Phone number</th>
      <th>Delivered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.text %></td>
        <td><%= message.phone_number %></td>
        <td><%= message.delivered %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

backend/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

backend/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @message.phone_number %>
</p>

<p>
  <strong>Delivered:</strong>
  <%= @message.delivered %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>